# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa1723a22e9392b3541d0d30d6575942448b6ad4784ce709694dbc654bdd784f77a39f9d934fdc89780954326b988b1ece61f157d82e86dc0a3852890ef48ea

test:
  secret_key_base: a30ba64d81d973d6a56018ac41bd59af3be74ca8494c2387f4564d0b38c6f549ed8aaef19b7d9db999f52c48292237abe207869010237a77b3432654dc1f579f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
